Repository puppetlabs/ca_extend, pull requests merged in 2021-08, with the labels that each got.

#30 Remove hard-coded paths from scripts
  tasks/check_ca_expiry.sh
  tasks/configure_master.sh
Labels: bug

#37 Update plans to comply with puppet strings
  REFERENCE.md
  plans/extend_ca_cert.pp
  plans/get_agent_facts.pp
  plans/upload_ca_cert.pp
Labels: maintenance

#39 (SUP-2497) Remove EOL platforms and versions
  metadata.json
Labels: backwards-incompatible

#40 Remove harmful terms from ca_extend
  README.md
  plans/extend_ca_cert.pp
  tasks/configure_primary.json
  tasks/configure_primary.sh
Labels: backwards-incompatible
